SET IDENTITY_INSERT [dbo].[Tests] ON
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (1, N'Complete Blood Count (CBC)', CAST(500.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (2, N'Blood Glucose Test', CAST(300.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (3, N'Lipid Panel', CAST(700.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (4, N'Liver Function Tests (LFTs)', CAST(600.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (5, N'Kidney Function Tests', CAST(550.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (6, N'Thyroid Function Test', CAST(650.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (7, N'Hemoglobin A1c', CAST(500.00 AS Decimal(18, 2)), 1)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (8, N'Urinalysis', CAST(200.00 AS Decimal(18, 2)), 2)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (9, N'Urine Culture', CAST(500.00 AS Decimal(18, 2)), 2)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (10, N'24- Hour Urine collection', CAST(700.00 AS Decimal(18, 2)), 2)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (11, N'X-ray', CAST(800.00 AS Decimal(18, 2)), 3)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (12, N'Ultrasound', CAST(1500.00 AS Decimal(18, 2)), 3)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (13, N'MRI (Magnetic Resonance Imaging)', CAST(5000.00 AS Decimal(18, 2)), 3)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (14, N'CT Scan (Computed Tomography)', CAST(4000.00 AS Decimal(18, 2)), 3)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (15, N'Throat Culture', CAST(500.00 AS Decimal(18, 2)), 4)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (16, N'Stool Culture', CAST(600.00 AS Decimal(18, 2)), 4)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (17, N'Blood Culture', CAST(1000.00 AS Decimal(18, 2)), 4)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (18, N'Karyotyping', CAST(4000.00 AS Decimal(18, 2)), 5)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (19, N'BRCA Gene Test', CAST(10000.00 AS Decimal(18, 2)), 5)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (20, N'Newborn Screening', CAST(3000.00 AS Decimal(18, 2)), 5)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (21, N'Testosterone Levels', CAST(800.00 AS Decimal(18, 2)), 6)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (22, N'Estrogen Levels', CAST(900.00 AS Decimal(18, 2)), 6)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (23, N'Cortisol Levels', CAST(850.00 AS Decimal(18, 2)), 6)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (24, N'PSA (Prostate-Specific Antigen) Test', CAST(700.00 AS Decimal(18, 2)), 7)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (25, N'CA-125', CAST(800.00 AS Decimal(18, 2)), 7)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (26, N'Mammography', CAST(2000.00 AS Decimal(18, 2)), 7)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (27, N'HIV Test', CAST(500.00 AS Decimal(18, 2)), 8)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (28, N'Hepatitis Panel', CAST(1500.00 AS Decimal(18, 2)), 8)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (29, N'Autoantibody Tests', CAST(1200.00 AS Decimal(18, 2)), 8)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (30, N'Electrocardiogram (ECG/EKG)', CAST(400.00 AS Decimal(18, 2)), 9)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (31, N'Echocardiogram', CAST(2000.00 AS Decimal(18, 2)), 9)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (32, N'Stess Test', CAST(1500.00 AS Decimal(18, 2)), 9)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (33, N'Spirometry', CAST(500.00 AS Decimal(18, 2)), 10)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (34, N'Chest X-ray', CAST(800.00 AS Decimal(18, 2)), 10)
INSERT INTO [dbo].[Tests] ([TestId], [TestName], [Price], [DepartmentId]) VALUES (35, N'Arterial Blood Gas (ABG)', CAST(700.00 AS Decimal(18, 2)), 10)
SET IDENTITY_INSERT [dbo].[Tests] OFF
