SET IDENTITY_INSERT [dbo].[Cities] ON
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (2, N'Mumbai', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (3, N'Pune', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (4, N'Nagpur', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (5, N'Thane', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (6, N'Pimri chinchwad', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (7, N'Nashik', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (8, N'Aurangabad', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (9, N'Solapur', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (10, N'Kolhapur', 1)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (11, N'Panaji', 2)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (12, N'Ponda', 2)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (13, N'Mapusa', 2)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (14, N'Margao', 2)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (15, N'Vasco da Gama', 2)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (16, N'Changlang', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (17, N'Bomdila', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (18, N'Dirang', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (19, N'Dibang Valley', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (20, N'Ziro', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (21, N'Anjaw', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (22, N'Tirap', 3)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (23, N'Bhopal', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (24, N'Indore', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (25, N'Ratlam', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (26, N'Sagar', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (27, N'Rewa', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (28, N'Satna', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (29, N'Burhanpur', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (30, N'Khandwa', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (31, N'Katni', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (32, N'Gwalior', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (33, N'Sehore', 4)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (34, N'Agra', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (35, N'Varanasi', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (36, N'Jhansi', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (37, N'Firozabad', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (38, N'Prayagraj', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (39, N'Rampur', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (40, N'Aligarh', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (41, N'Noida', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (42, N'Bareilly', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (43, N'Fatehpur', 5)
INSERT INTO [dbo].[Cities] ([CityId], [CityName], [StateId]) VALUES (44, N'Mirzapur', 5)
SET IDENTITY_INSERT [dbo].[Cities] OFF
